config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'pages#index'

  get 'pages/about' => 'pages#about'
  get 'pages/professional' => 'pages#professional'
  get 'posts' => 'posts#show'

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def professional
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:date, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Blog</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">
  <link href='//fonts.googleapis.com/css?family=Roboto:400' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>

<footer class="footer">
  <div class="row">

    <div class="small-4 columns custom-hidden">
      Nothing to see here!
    </div>

    <div class="small-4 columns text-center">
      <h4 class="links">
        <a href="/"><i class="fi-home"></i></a>
        <a href="mailto:beltz08@me.com?Subject=You%20Are%20Rad"><i class="fi-mail"></i></a>
        <a href="//www.twitter.com/KikkiBeltz"><i class="fi-social-twitter"></i></a>
        <a href="//www.linkedin.com/in/kbeltz"><i class="fi-social-linkedin"></i></a>
        <a href="//www.github.com/KBeltz"><i class="fi-social-github"></i></a>
      </h4>
      <p class="copywrite">© 2015</p>
    </div>

    <div class="small-4 columns">
      <a href="/" class="button custom-button"> </a>
    </div>

  </div>
</footer>

</html>

app/views/pages/about.html.erb
<div class="custom-background">
  <br><br>
  <div class="row">
    <div class="small-12 medium-9 large-6 columns">
      <p class="gradient-button" onclick="showMe('professional'); hideMe('personal')">
        Professional
      </p>
    </div>
    <div class="small-12 medium-9 large-6 columns">
      <p class="gradient-button" onclick="showMe('personal'); hideMe('professional')">
        Personal
      </p>
    </div>
    <div>
      <div id="professional" style="display: block;">
        <br>
        <h4>Professional</h4>
        <p>
          I was a nuclear electrician's mate in the US Navy from 2003-2007. I was a third class petty officer stationed in Everett, Washington on the aircraft carrier CVN-72 USS Abraham Lincoln. I performed preventative and corrective maintenance, utilized lockout-tagout procedures, and complied with electrical safety controls and radiation safety controls. I also utilized schematics and shipboard diagrams to create and check complex tagout procedures to ensure personnel safety. Relevant equipment: turbine and diesel generators, pump motors, and salinity cells.
        </p>
        <p>
          From 2007-2008 I lived in Bozeman, MT and worked as a wiring technician at Pierry Manufacturing. I utilized schematics and technical knowledge to wire 450V industrial printing press dryer and 120V utility pump control panels according to customer specifications.
        </p>
        <p>
          In 2008 I moved to Georgia, where I completed my college education. In 2012 I graduated from North Georgia College and State University (now the University of North Georgia) with a Bachelor's of Science in Physics. From 2011-2012 I worked as a Physics II lab assistant and tutor at the school. I set up and monitored Physics II labs, assisted students with the collection and analysis of lab data, tutored students, and graded lab reports.
        </p>
      </div>
    </div>
    <div>
      <div id="personal" style="display: none;">
        <br>
        <h4>Personal</h4>
        <p>
          I am a volunteer manager at the Tip Top Thrift Shop in Benson. I have been volunteering there regularly since May of 2013. The store benefits Youth Emergency Services of Omaha through regular monetary donations and donations of household items to YES young adults in the transitional living program.
        </p>
        <p>
          I enjoy riding bikes for fitness and fun as well as for transportation. I led two small family-centered group rides, called Kidical Mass, through a local bike shop in 2015 and I look forward to leading more rides in the future.
        </p>
        <p>
          I am currently a purple belt in tae kwon do. I have been training for one year, and I plan to earn my black belt one day.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">
<section class="hero">

  <div class="row">
    <div class="large-4 columns">
      <h2 class="custom-link text-center"><%= link_to "ABOUT", pages_about_path %></h2>
    </div>
    <div class="large-4 columns">
      <h2 class="custom-link text-center"><%= link_to "EXPERIENCE", pages_professional_path %></h2>
    </div>
    <div class="large-4 columns">
      <h2 class="custom-link text-center"><%= link_to "BLOG", "http://kbeltz.github.io/" %></h2>
    </div>
  </div>

  <div class="row intro">
    <div class="small-centered medium-uncentered medium-6 large-7 columns">
      <h1>K. Beltz</h1>
      <p>Web Developer | Omaha, Nebraska</p>
    </div>
    <div class="small-centered medium-uncentered medium-6 large-5 columns">
      <div class="tech-img"></div>
    </div>
  </div>



</section>

app/views/pages/professional.html.erb
<br><br>
<div class="text-center">
  <h2>Recent Work</h2>
  <br><br>
  <ul>
    <li class="no-bullet small-10 medium-10 large-10">
      <h4><a href="https://aqueous-retreat-2523.herokuapp.com/">Omaha Bicycle Pedestrian Count</a>
</h4>
      <p>
        This project was developed during Omaha Code School for nonprofit Modeshift Omaha, an organization that advocates for transportation options throughout the city. This site is projected for use in 2016 to assist in the facilitation of a city-wide bicycle pedestrian count, to provide data to our city leaders so that they may allocate resources accordingly. The site was built with Ruby on Rails, with Bootstrap as the framework. A gem called ActiveAdmin was used as the administration framework, and Devise was used for authentication.
      </p>
    </li>
  </ul>

</div>
<br><br>
<div class="half-size">
  <%= image_tag("unicorn-galaxy.gif") %>
</div>
<br><br>
<%= link_to "Image Credit", "http://amylovespenguins.deviantart.com/" %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<br><br>
<div class="text-center">
  <h2>Coming Soon</h2>
</div>
<%= image_tag("unicorn-galaxy.gif") %>
<br><br>
<%= link_to "Image Credit", "http://amylovespenguins.deviantart.com/" %>
<!-- <table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Content</th>
    </tr>
  </thead> -->

  <!-- <tbody> -->
    <% @posts.each do |post| %>
      <tr>
        <td><% post.date %></td>
        <td><% link_to post.title, post %></td>
        <td><% post.content %></td>
      </tr>
    <% end %>
  <!-- </tbody>
</table>

<br> -->

<% link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @post.date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>